Fix mayavi imports in postprocess.utils
Using EPD the postproc.py script fails to import mlab (see below).
This commit changes the import syntax so that postproc.py runs
and produces the expected 3D window display.

PROBLEM
-------

epd-ccosmos$ postproc.py cylinder.vtk
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/aldcroft/soft/EPD/epd-7.2-1-rh5-x86_64/bin/postproc.py in <module>()
      6 import sfepy
      7 from sfepy.base.base import assert_, get_default, output, nm
----> 8 from sfepy.postprocess import Viewer, get_data_ranges, create_file_source
      9 from sfepy.postprocess.domain_specific import DomainSpecificPlot
     10

/home/aldcroft/soft/EPD/epd-7.2-1-rh5-x86_64/lib/python2.7/site-packages/sfepy/postprocess/__init__.py in <module>()
----> 1 from viewer import Viewer, ViewerGUI
      2 from utils import get_data_ranges
      3 from sources import FileSource, create_file_source

/home/aldcroft/soft/EPD/epd-7.2-1-rh5-x86_64/lib/python2.7/site-packages/sfepy/postprocess/viewer.py in <module>()
     31 from sfepy.linalg import cycle
     32 from sfepy.solvers.ts import get_print_info
---> 33 from sfepy.postprocess.utils import mlab
     34 from sfepy.postprocess.sources import create_file_source, FileSource
     35

/home/aldcroft/soft/EPD/epd-7.2-1-rh5-x86_64/lib/python2.7/site-packages/sfepy/postprocess/utils.py in <module>()
     12
     13 if mayavi:
---> 14     mlab = mayavi.mlab
     15     Source = mayavi.core.source.Source
     16     Filter = mayavi.core.filter.Filter

AttributeError: 'module' object has no attribute 'mlab'